# Generated by Django 4.1.13 on 2024-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangoutCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('max_slot_time', models.PositiveIntegerField()),
                ('max_people', models.PositiveIntegerField()),
                ('code', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
