# Generated by Django 5.1.1 on 2024-10-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangoutCode',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('max_slot_time', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_functionality.hangoutcode')),
            ],
        ),
        migrations.CreateModel(
            name='TimeInterval',
            fields=[
                ('tid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_functionality.userdata')),
            ],
        ),
    ]
