# Generated by Django 5.1.1 on 2024-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_functionality', '0002_userslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeinterval',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeinterval',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='UserSlot',
        ),
    ]
